FROM confluentinc/cp-kafka:8.0.0

# Baixar JMX Prometheus Exporter
USER root
RUN mkdir -p /opt/jmx-exporter && \
    curl -L https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.19.0/jmx_prometheus_javaagent-0.19.0.jar \
    -o /opt/jmx-exporter/jmx_prometheus_javaagent.jar && \
    chmod 644 /opt/jmx-exporter/jmx_prometheus_javaagent.jar

USER appuser